---
title: "Untitled"
output: html_document
date: "2024-12-10"
---

```         
<p>If we list all the natural numbers below $10$ that are multiples of $3$ or $5$, we get $3, 5, 6$ and $9$. The sum of these multiples is $23$.</p>
<p>Find the sum of all the multiples of $3$ or $5$ below $1000$.</p>
```

# problem 1 

```{r}
one_1k <- seq(1,1000)
                        # divisible by 3 or 5 and less than 1000
mul_3_5_lt_1k_sum <- one_1k[one_1k %% 3 == 0 | one_1k %% 5 == 0 & one_1k < 1000]

(sum(mul_3_5_lt_1k_sum))
```

correct

# problem 2

``` HTML
<p>Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with $1$ and $2$, the first $10$ terms will be:
$$1, 2, 3, 5, 8, 13, 21, 34, 55, 89, \dots$$</p>
<p>By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.</p>
```

```{r}
# alright so first we need a vector of the fibinati sequences up to 4 million VECTORISED
 x <- numeric(0)
 x[1] = 1
 x[2] = 2 

  
  i = 2
    
        repeat{
        
        i = i + 1 
          
        x[i] = x[i-1] + x[i-2]
        
        if ( x[i] >= 4000000) { break }
      
        }

  (sum(x[x %% 2 == 0]))
 
```

correct

# problem 3

```         
<p>The prime factors of $13195$ are $5, 7, 13$ and $29$.</p>
<p>What is the largest prime factor of the number $600851475143$?</p>
```

```{r}

check_prime <- function(x) {
  # if x is divisible by any number from 1 to itself minus 1 then it's not prime
  if ( x %% seq(1,x-1) == 0 ) {return(false)} #this is a vector of booleans
  else { return(TRUE) }
}



(check_prime(28287))

```
